# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gwvault < Formula
  desc "GoodwayGroup Ansible Vault - ansible-vault CLI reimplemented in go"
  homepage "https://goodwaygroup.github.io/gwvault/"
  version "2.1.5"
  license "MIT"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/GoodwayGroup/gwvault/releases/download/v2.1.5/gwvault_2.1.5_darwin_amd64.tar.gz"
      sha256 "ed46b3f5d59ab2a3c1e907e8def423df43e18f0538d8b667636312e1e8c4854d"
    end
    if Hardware::CPU.arm?
      url "https://github.com/GoodwayGroup/gwvault/releases/download/v2.1.5/gwvault_2.1.5_darwin_arm64.tar.gz"
      sha256 "f02491207c7c873123ed3353c81dd73ed990aee8453d906ed9c7b115e5570323"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/GoodwayGroup/gwvault/releases/download/v2.1.5/gwvault_2.1.5_linux_amd64.tar.gz"
      sha256 "247492ce65f5e48a533b2aaf29577eb3209ac872ffe3ea1435dc39eb1fa22a5e"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/GoodwayGroup/gwvault/releases/download/v2.1.5/gwvault_2.1.5_linux_armv6.tar.gz"
      sha256 "cc4d13f2d2ff46b6e618454c6f073eb6df23c27f5a598b961ea87c696bd8c825"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/GoodwayGroup/gwvault/releases/download/v2.1.5/gwvault_2.1.5_linux_arm64.tar.gz"
      sha256 "f4d074b97ca81438fda12fdc35f4da2ea064c0375bb290085eb171fd44d23ac1"
    end
  end

  def install
    bin.install "gwvault"
  end

  test do
    system "#{bin}/gwvault --help"
  end
end
